<a href="https://colab.research.google.com/github/zrabiabudak/MachineLearning/blob/main/Guided_project_4.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import pandas as pd
import seaborn as sns

In [3]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [4]:
data=pd.read_csv("/content/drive/MyDrive/Colab Notebooks/project3/Advertising.csv")
data=data.iloc[:,1:len(data)]
data.head(2)

TV  radio  newspaper  sales
0  230.1   37.8       69.2   22.1
1   44.5   39.3       45.1   10.4

In [5]:
X=data.drop("sales",axis=1)

In [6]:
y=data[["sales"]]

In [7]:
import statsmodels.api as sm

In [8]:
lineerModel=sm.OLS(y, X)

In [9]:
Model=lineerModel.fit()

In [10]:
Model.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                                 OLS Regression Results                                
=======================================================================================
Dep. Variable:                  sales   R-squared (uncentered):                   0.982
Model:                            OLS   Adj. R-squared (uncentered):              0.982
Method:                 Least Squares   F-statistic:                              3566.
Date:                Sat, 13 Aug 2022   Prob (F-statistic):                   2.43e-171
Time:                        11:38:59   Log-Likelihood:                         -423.54
No. Observations:                 200   AIC:                                      853.1
Df Residuals:                     197   BIC:                                      863.0
Df Model:                           3                                                  
Covariance Type:            nonrobust                                                  
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
TV             0.0538      0.001     40.507      0.000       0.051       0.056
radio          0.2222      0.009     23.595      0.000       0.204       0.241
newspaper      0.0168      0.007      2.517      0.013       0.004       0.030
==============================================================================
Omnibus:                        5.982   Durbin-Watson:                   2.038
Prob(Omnibus):                  0.050   Jarque-Bera (JB):                7.039
Skew:                          -0.232   Prob(JB):                       0.0296
Kurtosis:                       3.794   Cond. No.                         12.6
==============================================================================

Warnings:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
"""

In [11]:
from sklearn.linear_model import LinearRegression

In [12]:
lm=LinearRegression()

In [13]:
model=lm.fit(X, y)

In [14]:
model.intercept_

array([2.93888937])

In [15]:
model.coef_

array([[ 0.04576465,  0.18853002, -0.00103749]])

In [16]:
Model.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                                 OLS Regression Results                                
=======================================================================================
Dep. Variable:                  sales   R-squared (uncentered):                   0.982
Model:                            OLS   Adj. R-squared (uncentered):              0.982
Method:                 Least Squares   F-statistic:                              3566.
Date:                Sat, 13 Aug 2022   Prob (F-statistic):                   2.43e-171
Time:                        11:40:44   Log-Likelihood:                         -423.54
No. Observations:                 200   AIC:                                      853.1
Df Residuals:                     197   BIC:                                      863.0
Df Model:                           3                                                  
Covariance Type:            nonrobust                                                  
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
TV             0.0538      0.001     40.507      0.000       0.051       0.056
radio          0.2222      0.009     23.595      0.000       0.204       0.241
newspaper      0.0168      0.007      2.517      0.013       0.004       0.030
==============================================================================
Omnibus:                        5.982   Durbin-Watson:                   2.038
Prob(Omnibus):                  0.050   Jarque-Bera (JB):                7.039
Skew:                          -0.232   Prob(JB):                       0.0296
Kurtosis:                       3.794   Cond. No.                         12.6
==============================================================================

Warnings:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
"""

In [17]:
new_data=[[30],[10],[20]]

In [18]:
import pandas as pd
new_data=pd.DataFrame(new_data).T

In [19]:
new_data

0   1   2
0  30  10  20

In [20]:
model.predict(new_data)

/usr/local/lib/python3.7/dist-packages/sklearn/base.py:451: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  "X does not have valid feature names, but"


array([[6.17637904]])

In [21]:
model.predict(X)[0:10]

array([[20.52397441],
       [12.33785482],
       [12.30767078],
       [17.59782951],
       [13.18867186],
       [12.47834763],
       [11.72975995],
       [12.12295317],
       [ 3.72734086],
       [12.55084872]])

In [22]:
from sklearn.metrics import mean_squared_error

In [23]:
mean_squared_error(y, model.predict(X))

2.784126314510936

In [24]:
from sklearn.model_selection import train_test_split

In [43]:
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.20,random_state=99)

In [44]:
X_train.head()

TV  radio  newspaper
16    67.8   36.6      114.0
51   100.4    9.6        3.6
97   184.9   21.0       22.0
164  117.2   14.7        5.4
71   109.8   14.3       31.7

In [45]:
from sklearn.linear_model import LinearRegression
lm=LinearRegression()

In [46]:
Model=lm.fit(X_train, y_train)

In [48]:
import numpy as np

In [49]:
np.sqrt(mean_squared_error(y_train,model.predict(X_train)))

1.7244414935853614

In [50]:
np.sqrt(mean_squared_error(y_test,model.predict(X_test)))

1.423319259111964

In [60]:
model.predict(X_test)[0:5].T

array([[14.00141385,  6.599669  ,  8.42401933,  9.01603163,  6.82006767]])

In [59]:
y_test.head().T

135  127  191  66   119
sales  11.6  8.8  9.9  9.5  6.6

In [61]:
from sklearn.model_selection import cross_val_score

In [65]:
cross_val_score(model,X_train,y_train,cv=10,scoring="neg_mean_squared_error")

array([-2.1019073 , -2.48953197, -3.09704214, -2.34694216, -3.68175761,
       -1.8691401 , -3.18173007, -4.1927349 , -2.17128376, -8.03821974])

In [67]:
np.mean(-cross_val_score(model,X_train,y_train,cv=10,scoring="neg_mean_squared_error"))

3.3170289742341246